### ISSUE TITLE
타이머 오버레이 실행 시 잘려서 보이는 문제

### ISSUE THREAD

**Issue by gonudayo** [osamhack2021/Web_With_Military_temp#78]
![image](https://user-images.githubusercontent.com/68852158/153606614-9ef61d93-c9fa-46eb-ba19-0428df13b0d4.png)

- 그룹페이지 혹은 랭킹페이지에 처음 접속했을 때, 타이머 오버레이를 실행하면 
유저정보를 받아오고 오버레이가 활성화 되는데 잘려서 정상적으로 보이지 않음.
스크롤을 내리면 정상 위치로 되돌아 옴.
- 새롭게 유저정보를 받아오면서 시간이 걸리는지 활성화 되는데도 다른 곳 과는 다르게 오래 걸림.

**Comment by Seungho-Na** [comment]
해결했고 close하겠습니다.
